import React from 'react';
import { View, Text, StyleSheet, Dimensions } from 'react-native';
import { EmailDocument } from '../../types';

interface AIContentData {
  businessName: string;
  businessInitials: string;
  headline: string;
  tagline: string;
  bodyText: string;
  ctaText: string;
  ctaAction: string;
  contactInfo: string;
  heroImage?: string;
  logo?: string;
}

interface BrandData {
  colors: {
    primary: string;
    secondary: string;
    accent: string;
    text: string;
    background: string;
  };
  typography: {
    headingFont: string;
    bodyFont: string;
    personality: string;
  };
}

interface AISmartTemplateProps {
  aiContent: AIContentData;
  brandData: BrandData;
  onContentUpdate?: (content: Partial<AIContentData>) => void;
}

const { width: screenWidth } = Dimensions.get('window');

export const AISmartTemplate: React.FC<AISmartTemplateProps> = ({
  aiContent,
  brandData,
  onContentUpdate,
}) => {
  return (
    <View style={styles.container}>
      {/* Header Section */}
      <View style={[styles.header, { backgroundColor: brandData.colors.background }]}>
        <View style={[styles.logoContainer, { backgroundColor: brandData.colors.primary }]}>
          {aiContent.logo ? (
            <Text style={styles.logoPlaceholder}>📷</Text>
          ) : (
            <Text style={[styles.logoInitials, { color: brandData.colors.background }]}>
              {aiContent.businessInitials}
            </Text>
          )}
        </View>
        <Text style={[styles.businessName, { color: brandData.colors.text }]}>
          {aiContent.businessName}
        </Text>
      </View>

      {/* Hero Section */}
      <View style={[styles.heroSection, { backgroundColor: brandData.colors.secondary }]}>
        <View style={styles.heroImagePlaceholder}>
          <Text style={styles.heroImageIcon}>🖼️</Text>
          <Text style={styles.heroImageText}>AI Selected Image</Text>
        </View>
        <View style={[styles.heroOverlay, { backgroundColor: `${brandData.colors.primary}20` }]} />
      </View>

      {/* Content Section */}
      <View style={[styles.contentSection, { backgroundColor: brandData.colors.background }]}>
        <Text style={[styles.headline, { color: brandData.colors.primary }]}>
          {aiContent.headline}
        </Text>
        
        <Text style={[styles.tagline, { color: brandData.colors.accent }]}>
          {aiContent.tagline}
        </Text>
        
        <Text style={[styles.bodyText, { color: brandData.colors.text }]}>
          {aiContent.bodyText}
        </Text>
      </View>

      {/* CTA Section */}
      <View style={styles.ctaSection}>
        <View style={[styles.ctaButton, { backgroundColor: brandData.colors.primary }]}>
          <Text style={[styles.ctaText, { color: brandData.colors.background }]}>
            {aiContent.ctaText}
          </Text>
        </View>
      </View>

      {/* Footer */}
      <View style={[styles.footer, { backgroundColor: brandData.colors.accent }]}>
        <Text style={[styles.footerText, { color: brandData.colors.background }]}>
          {aiContent.contactInfo}
        </Text>
        <Text style={[styles.aiAttribution, { color: `${brandData.colors.background}80` }]}>
          ✨ Generated by AI Assistant
        </Text>
      </View>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    width: '100%',
    backgroundColor: '#ffffff',
    borderRadius: 8,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  
  // Header Styles
  header: {
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 16,
  },
  logoContainer: {
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
  },
  logoInitials: {
    fontSize: 24,
    fontWeight: 'bold',
  },
  logoPlaceholder: {
    fontSize: 30,
  },
  businessName: {
    fontSize: 20,
    fontWeight: '600',
    textAlign: 'center',
  },
  
  // Hero Styles
  heroSection: {
    height: 120,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
  },
  heroImagePlaceholder: {
    alignItems: 'center',
  },
  heroImageIcon: {
    fontSize: 40,
    marginBottom: 8,
  },
  heroImageText: {
    fontSize: 12,
    color: '#666',
    fontStyle: 'italic',
  },
  heroOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  
  // Content Styles
  contentSection: {
    paddingVertical: 24,
    paddingHorizontal: 20,
  },
  headline: {
    fontSize: 22,
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 8,
    lineHeight: 28,
  },
  tagline: {
    fontSize: 16,
    textAlign: 'center',
    marginBottom: 16,
    fontStyle: 'italic',
  },
  bodyText: {
    fontSize: 16,
    lineHeight: 24,
    textAlign: 'center',
  },
  
  // CTA Styles
  ctaSection: {
    paddingVertical: 20,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  ctaButton: {
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 25,
    minWidth: '60%',
    alignItems: 'center',
  },
  ctaText: {
    fontSize: 16,
    fontWeight: '600',
  },
  
  // Footer Styles
  footer: {
    paddingVertical: 16,
    paddingHorizontal: 20,
    alignItems: 'center',
  },
  footerText: {
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 4,
  },
  aiAttribution: {
    fontSize: 11,
    textAlign: 'center',
    fontStyle: 'italic',
  },
});

export default AISmartTemplate;